const database = new Database();

const popularEvents = [
  new Event("event1", "Hackaton", "2020-11-09", "conference", "images/confHacaton .png", "The world’s largest API Integration hackathon.", "API World is produced and owned by DevNetwork, the worlds developer event community and producer of leading conferences for the developer, engineering & IT industries. By registering for this event, you are opting into DevNetwork email updates and one-time email-based promotions from top-level API World 2020 sponsors including exclusive invitations to API World 2020 parties and partner events. These updates will notify you about API World 2020 news, as well as announcements about DevNetwork events and services. You can opt out of DevNetwork email updates at any time.", true),
  new Event("event2", "DeveloperWeek Global: Enterprise 2020", "2020-11-10", "conference", "images/conDevConf.jpeg", "DeveloperWeek Global is produced and owned by DevNetwork, the world's developer event community and producer of leading conferences for the developer, engineering & IT industries.", "DeveloperWeek Global is produced and owned by DevNetwork, the world's developer event community and producer of leading conferences for the developer, engineering & IT industries. By registering for this event, you are opting into DevNetwork email updates and one-time email-based promotions from top-level DeveloperWeek Global 2020 sponsors including exclusive invitations to DeveloperWeek Global 2020 parties and partner events. These updates will notify you about DeveloperWeek Global 2020 news, as well as announcements about DevNetwork events and services.", true),
  new Event("event3", "AI DevWorld 2020", "2020-11-10", "conference", "images/confAIDevWorld.jpeg", "AI & Machine Learning developer conference.", "AI DevWorld 2020 (October 27-29)) is the world’s largest AI & Machine Learning developer conference, with tracks covering: Open Source AI libraries, Chatbots, Machine Learning-as-a-Service, AI for the Enterprise, Deep AI/Neural Networks & more. The conference targets software engineers and data scientists who are looking for an introduction to AI, as well as AI dev professionals looking for a landscape view on the newest AI technologies. DeveloperWeek is produced and owned by DevNetwork, the world's developer event community and producer of leading conferences for the developer, engineering & IT industries. By registering for this event, you are opting into DevNetwork email updates and one-time email-based promotions from top-level AI DevWorld 2020 sponsors including exclusive invitations to AI DevWorld 2020 parties and partner events. These updates will notify you about AI DevWorld 2020 news, as well as announcements about DevNetwork events and services. You can opt out of DevNetwork email updates at any time.", true),
  new Event("event4", "Workshop: Introduction to Hacking", "2020-11-19", "class", "images/classIntrToHack.jpeg", "Take this intro course to learn how hackers use cryptography to protect (and steal) data.", "Data is one of the most valuable assets that anyone owns, which is why stealing data is the goal of many cyber attacks. In this beginner-level course, we'll take you into the world of cryptography, showing you how to hide and store data using this powerful tool. We’ll talk about some of the most common methods used to encrypt data, and show you some of the tactics used by black hat hackers to break that encryption. You'll learn a bit of theory, then go hands on with real-world encryption tools that cybersecurity practitioners use every day. This class is taught by Fullstack Cyber Bootcamp's Lead Instructor Corey Greenwald, in a live video classroom (via Zoom) with other students. You'll use some of the same learning tools that we use on campus, so this class will give you a good sense for what it's like to attend Fullstack Cyber Bootcamp. All that's needed to participate is a computer (Mac or Windows) and a stable internet connection. No experience required!", true),
  new Event("event5", "Intro to Coding Workshop", "2020-12-15", "class", "images/classIntroToCoding.jpeg", "Introduction to coding workshop for Refugees, Asylum Seekers and other people from disadvantaged backgrounds.", "Come and learn about the world of web development in our workshop. This workshop will cover the basic technical and soft skills required to start on a path towards a career in the tech sector. We will cover topics such as HTML basics, CSS Basics, and JS Basics.<br>Agenda<br>Intro to Coding workshop<br>13:00 - 13:10 Technical Set up<br>13:10 - 13:35 Introductory talk<br>13:35 - 14:10 Technical session<br>14:10 - 14:20 Break<br>14:20 - 15:00 Technical session<br>Preparation<br>This workshop is intended to assist you on the CodeYourFuture Intro to Coding Course.", true),
  new Event("event6", "Intro to Coding: HTML & CSS | Akademi GA", "2020-11-28", "class", "images/classIntroToCodHTML.jpeg", "Meet the programming languages that power the web, and write your first line of code.", "Step into the world of web development with General Assembly. During our introductory workshop, explore the building blocks of the web — HTML and CSS — and learn how you can apply these programming languages to develop your own simple sites. By writing your own lines of code, you’ll:<br>* Get a closer look at how the developer community and many different fields benefit from coding knowledge.<br>* Learn how HTML and CSS function together to form the backbone of the web.<br>* Cover key coding terms and principles.<br>* Develop a custom, working web page from scratch.<br>Chart your own career path. Pick up where this workshop leaves off. Design and build a custom site online in our mentor-guided HTML, CSS, & Web Design On Demand Course. Incorporate JavaScript and code dynamic sites in our part-time, on-campus Front-End Web Development course. Or, go all-in and become a job-ready developer our 12-week, full-time Web Development Immersive program, available on campus and online. Please note that in light of the current COVID-19 situation, the class will be livestreamed to ensure the safety and well-being of all participants. Please register as per normal and you will be sent a Zoom link to join the livestream session.", true),
  new Event("event7", "VIRTUAL Software Engineering Course: Info Session", "2020-10-30", "networking", "images/nwVIRSoftwareEngiC.jpeg", "Are you curious about how you can transition your career to one in Software Engineering? Learn how with Flatiron School San Francisco!", "About this Event<br>Join a Flatiron School San Francisco Campus Director over Zoom to learn everything you need to know about how we can help make this possible through our Software Engineering course!<br>Takeaways<br>* What it's like to study at Flatiron School (In person vs Online courses)<br>* Admissions Process<br>* Financing<br>* Career Services<br>* Cohort start dates<br>*You will receive a Zoom link on the day of the event!<br>See you there!", true),
  new Event("event8", "CODE + BREWS Virtual", "2020-11-02", "networking", "images/netwCODEBREWSVirt.jpeg", "CODE + BREWS Virtual is back!", "CODE + BREWS Virtual is an inclusive, informal, co-working session for the developer community. People of all skill levels are invited to participate. The concept is simple, bring a laptop, coffee, breakfast, and ideas, and prepare to learn a new technical skill or, work on a side project, homework, or work.<br>Here's how it works:<br>1. At 9:15 everyone introduces themselves and briefly describes what brought them to CODE + BREWS today (projects, homework, networking, etc).<br>2. For the rest of the day, folks work in the digital space on their projects providing one another help and conversation as needed. Oh, and they usually drink coffee.<br>Where is the event?<br>This event will be hosted online through Zoom. We will send information on how to access Zoom securely the morning of the event.<br>Who can attend?<br>If you want to code (anything) and are at any skill level CODE + BREWS is for you. We are an inclusive group, focused on sharing skills and building Milwaukee's developer community.<br>Who is helping promote this event?<br>We are not a meetup or user group so we have partnered with local groups to help us promote and build CODE + BREWS community.", true),
  new Event("event9", "Code Together | North MS", "2020-12-17", "networking", "images/netwCoceTogether.jpeg", "A free community coding session", "Interested in coding with other people or getting help on a project that you're working on? If you said yes to this, then this might be the event for you! This Code Together event is a time for you to work alongside and connect with other people in your local community. Now, it's important to note that this isn't a class, so there won't be a teacher, but it is your opportunity to talk with other people and get help jumpstarting your learning process or with a programming lesson / personal project you've been working on. Come with your laptop, a notebook & pen, and/or a drive to learn! 1:00PM MEETUP INFO: We'll be meeting online via Zoom.", true)
];

document.addEventListener("DOMContentLoaded", () => {
  let events = database.readDataFromStorage();
  if (events.length == 0) {
    database.saveDataToStorage(popularEvents);
    events = popularEvents;
  }

  let eventsContainer = document.getElementById('mainContent');
  eventsContainer.innerHTML = '';
  // for each event from localStorage with flag (true)
  events
    .filter(item => item.popularEvent)
    .forEach((item) => {
    eventDiv = document.createElement('div');
    eventDiv.setAttribute('class', 'photo');
    eventDiv.setAttribute('id', item.id);
    eventDiv.setAttribute('data-title', item.name);
    eventsContainer.appendChild(eventDiv);

    let img = document.createElement('img');
    img.setAttribute('class', 'photo');
    img.setAttribute('src', item.img);
    eventDiv.appendChild(img);
    img.addEventListener("click", function () {
      document.location.href = 'eventTitell.html?id=' + item.id;
    })
  });
});
